name: flutter_injected_web3
description: A web3 injection library for flutter.
version: 1.0.1
homepage: https://github.com/Orange-Wallet/flutter_injected_web3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_inappwebview: ^6.0.0
  flutter:
    sdk: flutter
dev_dependencies:
  lints:
  test:

flutter:
  uses-material-design: true
  assets:
    - packages/flutter_injected_web3/assets/provider.min.js
